services:
  umbrelos:
    build: .
    image: umbrelos:latest
    restart: always
    stop_grace_period: 1m
    privileged: true
    ports:
      - "80:80"
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - ./umbrel:/data
